CREATE TABLE `timer` (
  `gregorian` varchar(10) character set utf8 NOT NULL COMMENT '公历',
  `g_shortbars` varchar(10) character set utf8 NOT NULL COMMENT '公历短杠',
  `g_backslash` varchar(10) character set utf8 NOT NULL COMMENT '公历反斜杠',
  `g_short` varchar(10) character set utf8 NOT NULL COMMENT '短公历',
  `lunar` varchar(10) character set utf8 NOT NULL COMMENT '阴历',
  `dayofyear` int(11) NOT NULL COMMENT '第几天',
  `weekofyear` int(11) NOT NULL COMMENT '第几周',
  `dayofweek` int(11) NOT NULL COMMENT '周内第几天',
  `year_num` int(11) NOT NULL COMMENT '数字年',
  `month_num` int(11) NOT NULL COMMENT '数字月',
  `day_num` int(11) NOT NULL COMMENT '数字天',
  `season_num` int(11) NOT NULL COMMENT '数字季度',
  `year_cn` varchar(10) character set utf8 NOT NULL COMMENT '中文年',
  `month_cn` varchar(10) character set utf8 NOT NULL COMMENT '中文月(数字)',
  `month_allcn` varchar(10) character set utf8 NOT NULL COMMENT '中文月',
  `day_cn` varchar(10) character set utf8 NOT NULL COMMENT '中文天',
  `week_cn` varchar(10) character set utf8 NOT NULL COMMENT '中文周',
  `season_cn` varchar(10) character set utf8 NOT NULL COMMENT '中文季度',
  `tendays` varchar(10) character set utf8 NOT NULL COMMENT '月旬',
  `halfyear` varchar(10) character set utf8 NOT NULL COMMENT '半年',
  `month_en` varchar(10) character set utf8 NOT NULL COMMENT '英文星期',
  `week_en` varchar(10) character set utf8 NOT NULL COMMENT '英文星期',
  PRIMARY KEY  (`gregorian`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;